### ISSUE TITLE
Optionally do not merge if a requested reviewer has left a comment review but not an approval

### ISSUE THREAD

**Issue by lpil** [EmbarkStudios/octobors#11]
Today we had a PR merged when the last remaining requested reviewer left a comment review rather than an approval. This was surprising to the author and reviewers of the PR as it was expected that all requested reviewers would need to approve.

This happened because GitHub considered a comment review enough, so it removes it from the list of remaining requested reviews. This leaves Octobors with only the state of the reviews, and a comment review does not prevent a PR from merging when it has sufficient approvals otherwise.

Sadly it is non-trivial to resolve this as GitHub does not expose any information in their API about historical review requests, so we cannot decide ourselves whether they have been done (as GitHub's logic is too permissive).

The information is in the HTML UI, but with private repos behind MFA we are unable to scrape this UI.

We could persist some state within Redis or similar about the historical status of the PR, but this is a bunch more complexity.

Perhaps this is to be solved socially by adjusting our expectations or process slightly? A tricky one.

**Comment by h3r2tic** [comment]
I started my review by adding a single comment, and that turned out to be the end of my review :stuck_out_tongue: https://github.com/EmbarkStudios/ark-modules/pull/1492

**Comment by lpil** [comment]
I've been studying GitHub's API and there's one scenario that I don't understand how to handle with the data they expose:

If Octobors is stateful we can keep track of the people who have been added as reviewers and as such we know not to consider a comment a review, even though GitHub says that a review is no longer required.

This solves the problem at hand but how do we support removing requested reviewers? This fact that a reviewer has been removed is present in the UI (inaccessible to the bot thanks to single sign on) but not in the API. From looking at Ark PRs is seems to be relatively common for people to remove some of the reviewers from PRs if they have enough existing reviews or the person is not available.

We might be able to guess whether the reviewer is no longer "required" by checking if they have left a comment since last analysis and otherwise considering it removed. It could be a little error prone perhaps, haven't thought through how to model that one exactly yet.
