### ISSUE TITLE
Attempt to automatically keep PRs updated

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/octobors#3]
It's useful to keep a PR updated with the branch it is going to be merged into, Github supports merging from the base branch as a preview feature, but doesn't support rebasing, so the easiest would just be to support both in the bot. This could either use the CLI or libgit2, though I would lean towards the CLI since it would 0 extra compile time/binary size for something that is (probably) available in the action environment.

**Comment by bnjbvr** [comment]
+1 to this; maybe a slightly different, simpler feature would be to try to rebase once the PR has been approved, just before a merge? (And comment if automatic rebase can't be done.)
This would avoid _merge skew_ ([see also](https://bors.tech/essay/2017/02/02/pitch/)) and make sure that green CI on PR implies the CI is green on main too.
